In [ ]:
#step1
import numpy as np
#step2
A = np.array([[0,1],[2,3],[4,5]])
B = np.array([[0,1,2,3],[4,5,6,7]])
#step3
C = np.dot(A,B)
#step4
print(C)
#step5
print(np.max(C))

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
47
